set_property IOSTANDARD LVCMOS33 [get_ports clk_i_w]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i_w]
# set_property IOSTANDARD LVCMOS33 [get_ports rxd]
# set_property IOSTANDARD LVCMOS33 [get_ports txd]
set_property PACKAGE_PIN K17 [get_ports clk_i_w]
set_property PACKAGE_PIN M19 [get_ports rst_i_w]
# set_property PACKAGE_PIN P15 [get_ports rxd]
# set_property PACKAGE_PIN U15 [get_ports txd]
